
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designervCQBqC.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(557, 376)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Menu = QWidget(self.centralwidget)
        self.Menu.setObjectName(u"Menu")
        self.Menu.setEnabled(True)
        self.Menu.setGeometry(QRect(40, 20, 481, 311))
        self.add = QPushButton(self.Menu)
        self.add.setObjectName(u"add")
        self.add.setGeometry(QRect(30, 30, 171, 61))
        self.sub = QPushButton(self.Menu)
        self.sub.setObjectName(u"sub")
        self.sub.setGeometry(QRect(280, 30, 171, 61))
        self.mul = QPushButton(self.Menu)
        self.mul.setObjectName(u"mul")
        self.mul.setGeometry(QRect(280, 130, 171, 61))
        self.div = QPushButton(self.Menu)
        self.div.setObjectName(u"div")
        self.div.setGeometry(QRect(30, 130, 171, 61))
        self.pushButton_5 = QPushButton(self.Menu)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(150, 230, 171, 61))
        self.Add = QWidget(self.centralwidget)
        self.Add.setObjectName(u"Add")
        self.Add.setGeometry(QRect(20, 50, 521, 251))
        self.Add.setVisible(False)
        self.x = QLineEdit(self.Add)
        self.x.setObjectName(u"x")
        self.x.setGeometry(QRect(40, 50, 91, 71))
        self.y = QLineEdit(self.Add)
        self.y.setObjectName(u"y")
        self.y.setGeometry(QRect(210, 50, 91, 71))
        self.label = QLabel(self.Add)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 80, 51, 21))
        self.label.setMinimumSize(QSize(2, 2))
        self.label.setSizeIncrement(QSize(2, 2))
        self.label.setBaseSize(QSize(2, 2))
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(2)
        self.label.setMargin(20)
        self.label.setIndent(-1)
        self.label_2 = QLabel(self.Add)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 80, 51, 21))
        self.label_2.setMinimumSize(QSize(2, 2))
        self.label_2.setSizeIncrement(QSize(2, 2))
        self.label_2.setBaseSize(QSize(2, 2))
        self.label_2.setFrameShadow(QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setMidLineWidth(2)
        self.label_2.setMargin(20)
        self.label_2.setIndent(-1)
        self.add_Res = QLabel(self.Add)
        self.add_Res.setObjectName(u"add_Res")
        self.add_Res.setGeometry(QRect(400, 80, 58, 16))
        self.doAdd = QPushButton(self.Add)
        self.doAdd.setObjectName(u"doAdd")
        self.doAdd.setGeometry(QRect(140, 180, 111, 51))
        self.pushButton_7 = QPushButton(self.Add)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(270, 180, 111, 51))
        self.Sub = QWidget(self.centralwidget)
        self.Sub.setObjectName(u"Sub")
        self.Sub.setGeometry(QRect(20, 50, 571, 251))
        self.Sub.setVisible(False)
        self.x_3 = QLineEdit(self.Sub)
        self.x_3.setObjectName(u"x_3")
        self.x_3.setGeometry(QRect(40, 50, 91, 71))
        self.y_3 = QLineEdit(self.Sub)
        self.y_3.setObjectName(u"y_3")
        self.y_3.setGeometry(QRect(210, 50, 91, 71))
        self.label_7 = QLabel(self.Sub)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 80, 51, 21))
        self.label_7.setMinimumSize(QSize(2, 2))
        self.label_7.setSizeIncrement(QSize(2, 2))
        self.label_7.setBaseSize(QSize(2, 2))
        self.label_7.setFrameShadow(QFrame.Plain)
        self.label_7.setLineWidth(2)
        self.label_7.setMidLineWidth(2)
        self.label_7.setMargin(20)
        self.label_7.setIndent(-1)
        self.label_8 = QLabel(self.Sub)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(330, 80, 51, 21))
        self.label_8.setMinimumSize(QSize(2, 2))
        self.label_8.setSizeIncrement(QSize(2, 2))
        self.label_8.setBaseSize(QSize(2, 2))
        self.label_8.setFrameShadow(QFrame.Plain)
        self.label_8.setLineWidth(2)
        self.label_8.setMidLineWidth(2)
        self.label_8.setMargin(20)
        self.label_8.setIndent(-1)
        self.sub_Res = QLabel(self.Sub)
        self.sub_Res.setObjectName(u"sub_Res")
        self.sub_Res.setGeometry(QRect(400, 80, 58, 16))
        self.doSub = QPushButton(self.Sub)
        self.doSub.setObjectName(u"doSub")
        self.doSub.setGeometry(QRect(140, 180, 111, 51))
        self.pushButton_11 = QPushButton(self.Sub)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(270, 180, 111, 51))
        self.Mul = QWidget(self.centralwidget)
        self.Mul.setObjectName(u"Mul")
        self.Mul.setGeometry(QRect(20, 50, 571, 251))
        self.Mul.setVisible(False)
        self.x_6 = QLineEdit(self.Mul)
        self.x_6.setObjectName(u"x_6")
        self.x_6.setGeometry(QRect(40, 50, 91, 71))
        self.y_6 = QLineEdit(self.Mul)
        self.y_6.setObjectName(u"y_6")
        self.y_6.setGeometry(QRect(210, 50, 91, 71))
        self.label_16 = QLabel(self.Mul)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(150, 80, 51, 21))
        self.label_16.setMinimumSize(QSize(2, 2))
        self.label_16.setSizeIncrement(QSize(2, 2))
        self.label_16.setBaseSize(QSize(2, 2))
        self.label_16.setFrameShadow(QFrame.Plain)
        self.label_16.setLineWidth(2)
        self.label_16.setMidLineWidth(2)
        self.label_16.setMargin(20)
        self.label_16.setIndent(-1)
        self.label_17 = QLabel(self.Mul)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(330, 80, 51, 21))
        self.label_17.setMinimumSize(QSize(2, 2))
        self.label_17.setSizeIncrement(QSize(2, 2))
        self.label_17.setBaseSize(QSize(2, 2))
        self.label_17.setFrameShadow(QFrame.Plain)
        self.label_17.setLineWidth(2)
        self.label_17.setMidLineWidth(2)
        self.label_17.setMargin(20)
        self.label_17.setIndent(-1)
        self.mul_Res = QLabel(self.Mul)
        self.mul_Res.setObjectName(u"mul_Res")
        self.mul_Res.setGeometry(QRect(400, 80, 58, 16))
        self.doMul = QPushButton(self.Mul)
        self.doMul.setObjectName(u"doMul")
        self.doMul.setGeometry(QRect(140, 180, 111, 51))
        self.pushButton_17 = QPushButton(self.Mul)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(270, 180, 111, 51))
        self.Div = QWidget(self.centralwidget)
        self.Div.setObjectName(u"Sub_2")
        self.Div.setGeometry(QRect(20, 50, 571, 251))
        self.Div.setVisible(False)
        self.x_8 = QLineEdit(self.Div)
        self.x_8.setObjectName(u"x_8")
        self.x_8.setGeometry(QRect(40, 50, 91, 71))
        self.y_8 = QLineEdit(self.Div)
        self.y_8.setObjectName(u"y_8")
        self.y_8.setGeometry(QRect(210, 50, 91, 71))
        self.label_22 = QLabel(self.Div)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(150, 80, 51, 21))
        self.label_22.setMinimumSize(QSize(2, 2))
        self.label_22.setSizeIncrement(QSize(2, 2))
        self.label_22.setBaseSize(QSize(2, 2))
        self.label_22.setFrameShadow(QFrame.Plain)
        self.label_22.setLineWidth(2)
        self.label_22.setMidLineWidth(2)
        self.label_22.setMargin(20)
        self.label_22.setIndent(-1)
        self.label_23 = QLabel(self.Div)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(330, 80, 51, 21))
        self.label_23.setMinimumSize(QSize(2, 2))
        self.label_23.setSizeIncrement(QSize(2, 2))
        self.label_23.setBaseSize(QSize(2, 2))
        self.label_23.setFrameShadow(QFrame.Plain)
        self.label_23.setLineWidth(2)
        self.label_23.setMidLineWidth(2)
        self.label_23.setMargin(20)
        self.label_23.setIndent(-1)
        self.div_Res = QLabel(self.Div)
        self.div_Res.setObjectName(u"div_Res")
        self.div_Res.setGeometry(QRect(400, 80, 58, 16))
        self.doDiv = QPushButton(self.Div)
        self.doDiv.setObjectName(u"doDiv")
        self.doDiv.setGeometry(QRect(140, 180, 111, 51))
        self.pushButton_21 = QPushButton(self.Div)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(270, 180, 111, 51))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 557, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_7.clicked.connect(self.Add.hide)
        self.pushButton_7.clicked.connect(self.Menu.show)
        self.pushButton_17.clicked.connect(self.Mul.hide)
        self.pushButton_17.clicked.connect(self.Menu.show)
        self.pushButton_11.clicked.connect(self.Sub.hide)
        self.pushButton_11.clicked.connect(self.Menu.show)
        self.pushButton_21.clicked.connect(self.Div.hide)
        self.pushButton_21.clicked.connect(self.Menu.show)
        self.pushButton_5.clicked.connect(MainWindow.close)
        self.add.clicked.connect(self.Menu.hide)
        self.add.clicked.connect(self.Add.show)
        self.sub.clicked.connect(self.Menu.hide)
        self.sub.clicked.connect(self.Sub.show)
        self.div.clicked.connect(self.Menu.hide)
        self.div.clicked.connect(self.Div.show)
        self.mul.clicked.connect(self.Menu.hide)
        self.mul.clicked.connect(self.Mul.show)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.add.setText(QCoreApplication.translate("MainWindow", u"Addition", None))
        self.sub.setText(QCoreApplication.translate("MainWindow", u"Subtraction", None))
        self.mul.setText(QCoreApplication.translate("MainWindow", u"Multiplication", None))
        self.div.setText(QCoreApplication.translate("MainWindow", u"Division", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.add_Res.setText("")
        self.doAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.sub_Res.setText("")
        self.doSub.setText(QCoreApplication.translate("MainWindow", u"Sub", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.mul_Res.setText("")
        self.doMul.setText(QCoreApplication.translate("MainWindow", u"Mult", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.div_Res.setText("")
        self.doDiv.setText(QCoreApplication.translate("MainWindow", u"Div", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"Back", None))
    # retranslateUi

